//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mark_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinav12
    {
        public int Sira { get; set; }
        public string Ders { get; set; }
        public string Derslik { get; set; }
        public string Gözetmen { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
